### ISSUE TITLE
file is offsync

### ISSUE THREAD

**Issue by arceuss** [ItzFireable/mania2fnf#2]
i converted a file from stepmania to osu mania but when converted to fnf the notes are offsync

[mania2fnf-master.zip](https://github.com/ItzFireable/mania2fnf/files/6605287/mania2fnf-master.zip) < includes the files used

**Comment by ItzFireable** [comment]
you sure the offset doesn't come from you converting sm to osu!mania? that's usually something that generates offset, from my past experience.

i'll look into this later, but can you try converting a chart from osu!mania in comparison? just so we can see if the issue is with my converter or theirs.

**Comment by arceuss** [comment]
> 
> 
> you sure the offset doesn't come from you converting sm to osu!mania? that's usually something that generates offset, from my past experience.
> 
> i'll look into this later, but can you try converting a chart from osu!mania in comparison? just so we can see if the issue is with my converter or theirs.

i tried raindrop and the file seems on sync now so its most likely the converter i used

**Comment by ItzFireable** [comment]
yeah, mania2fnf doesn't touch offset at all so i was wondering.
