### ISSUE TITLE
files cause a crash on fnf modding+ latest dev build

### ISSUE THREAD

**Issue by arceuss** [ItzFireable/mania2fnf#3]
https://streamable.com/vrenud example

**Comment by arceuss** [comment]
https://github.com/TheDrawingCoder-Gamer/Funkin/actions/runs/929966147 the build im using

**Comment by ItzFireable** [comment]
never used modding+, and i have no support for them.

i'm not going to add specific support for them, as it is (from my experience) one of the worst engines. they can fix it on their side, if they want.

kade engine is more playable for majority of the community, although has a bit of a learning curve.

**Comment by ItzFireable** [comment]
reopen if you have a bug related to the converter and not the engine.

**Comment by arceuss** [comment]
p sure the only issue is that the section is too long and haxe seems to only go up to 999

**Comment by arceuss** [comment]
> 
> 
> reopen if you have a bug related to the converter and not the engine.

p sure the only issue is that the section is too long and haxe seems to only go up to 999

**Comment by ItzFireable** [comment]
section being too long is an issue, but only in fnf modding+ from what i've seen.

i haven't found a way to efficiently split them into sections, and i'm not going to update this much unless something game breaking happens.

**Comment by arceuss** [comment]
i havent tried any other engines so who knows

**Comment by ItzFireable** [comment]
i recommend using kade engine, it may be harder to make mods on but it's way better feature wise.

other ones that have no issues are mic'd up engine and fps+, so far the only engine that doesn't like the converter is modding+.

**Comment by arceuss** [comment]
ok i just made another song in modding+ and now the chart doesnt crash
odd
